[project]
name = "python-web-framework-stars"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.4",
    "matplotlib>=3.7.0",
]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
extend-select = ["I"]