name: Run fetcher (daily)

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Run fetcher to update repository data and README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "=== Running fetcher.py ==="
          uv run python/fetcher.py

      - name: Debug file status
        run: |
          echo "=== Current directory contents ==="
          ls -la
          echo "=== repo_data directory contents ==="
          ls -la repo_data/ || echo "repo_data directory not found"
          echo "=== Git status ==="
          git status --porcelain
          echo "=== Checking specific files ==="
          test -f README.md && echo "README.md exists" || echo "README.md missing"

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md repo_data/
          git diff --cached --name-only
          git commit -m "Update repository data and README - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
